import os

# Files listed in vite.config.js (extracted manually or via script)
# For now, I'll just check a few likely culprits or write a quick parser.
# Actually, I'll just check the likely ones.

files_to_check = [
    'about.html',
    'contact.html',
    'index.html',
    'news.html',
    'products.html',
    'products/aluminum-foil/aluminum-foil-bag.html',
    'products/flat-handle/flat-handle-bag.html',
    'products/flathandle.html',
    'products/flathandle/christmas-series-flat-handle-bag.html',
    'products/flathandle/cream-color-flat-handle-bag.html',
    'products/flathandle/macaron-color-flat-handle-bag.html',
    'products/flathandle/recycled-kraft-flat-handle-sacks.html',
    'products/flathandle/single-color-shopping-bags.html',
    'products/foil.html',
    'products/foil/aluminum-foil-lined-bags.html',
    'products/fruit-protection/mango-bag.html',
    'products/greaseproof.html',
    'products/greaseproof/bakery-paper-bag.html',
    'products/greaseproof/bakery-paper-bags.html',
    'products/greaseproof/bakery-series-paper-bags.html',
    'products/greaseproof/bakery-side-window-bag.html',
    'products/greaseproof/banh-mi-paper-bags.html',
    'products/greaseproof/checkered-food-grade-wrap-paper.html',
    'products/greaseproof/deli-wrap.html',
    'products/greaseproof/die-cut-handle-round-hole-bags.html',
    'products/greaseproof/double-layer-paper-bag.html',
    'products/greaseproof/easy-use-die-cut-handle-paper-bags.html',
    'products/greaseproof/fancy-2-side-open-paper-bag.html',
    'products/greaseproof/french-baguette-bag.html',
    'products/greaseproof/fried-bread-stick-paper-bag.html',
    'products/greaseproof/greaseproof-paper-round-hole-bags.html',
    'products/greaseproof/lv-paper-bags.html',
    'products/greaseproof/news-2-side-open-paper-bag.html',
    'products/greaseproof/pfas-free-sandwich-bags.html',
    'products/greaseproof/pinhole-window-greaseproof-bag.html',
    'products/greaseproof/recycled-kraft-merchandise-paper-bags.html',
    'products/greaseproof/round-hole-bags.html',
    'products/greaseproof/small-2-side-open-bag.html',
    'products/greaseproof/solo-snack-bag-round-open.html',
    'products/greaseproof/tear-open-paper-bag.html',
    'products/greaseproof/thank-you-greaseproof-paper-bag.html',
    'products/greaseproof/the-pe-coated-paper-bags.html',
    'products/greaseproof/toast-bags.html',
    'products/greaseproof/toast-bags-have-tearble-line.html',
    'products/kraft.html',
    'products/kraft/8-square-bottom-paper-bag.html',
    'products/kraft/baguette-bakery-bag.html',
    'products/kraft/bakery-series-paper-bags.html',
    'products/kraft/bakery-window-bag.html',
    'products/kraft/christmas-series-square-bottom-paper-bag.html',
    'products/kraft/cream-color-square-bag.html',
    'products/kraft/die-cut-handle-bag.html',
    'products/kraft/flat-handle-grocery-bags.html',
    'products/kraft/hexagonal-bottom-paper-bag.html',
    'products/kraft/merchandise-bags.html',
    'products/kraft/sos-white-take-out-bags.html',
    'products/kraft/square-paper-bag.html',
    'products/kraft/to-go-sos-bags.html',
    'products/others.html',
    'products/others/bakery-side-window-bag.html',
    'products/others/paper-placement.html',
    'products/others/wonderful-time-paper-placemats.html',
    'products/paper-straw/paper-straw.html',
    'products/pe.html',
    'products/pe/burger-pocket-paper-bag.html',
    'products/pe/deli-wrap-paper.html',
    'products/pe-lamination/l-bag.html',
    'products/pe/toast-bags.html',
    'products/straw.html',
    'products/straw/biodegradable-bamboo-straw.html',
    'products/straw/paper-straw-brown.html',
    'products/white.html',
    'products/white-kraft/white-kraft-bag.html',
    'products/white/new-flate-handle-paper-bags.html',
    'products/white/recycled-kraft-grocery-bags.html',
    'products/white/take-out-bags-square-bottom-paper-bag.html',
    'products/white/white-kraft-bags.html',
    'zh-tw/about.html',
    'zh-tw/contact.html',
    'zh-tw/index.html',
    'zh-tw/news.html',
    'zh-tw/products.html',
    'zh-tw/products/aluminum-foil/aluminum-foil-bag.html',
    'zh-tw/products/flat-handle/flat-handle-bag.html',
    'zh-tw/products/flathandle.html',
    'zh-tw/products/flathandle/christmas-series-flat-handle-bag.html',
    'zh-tw/products/flathandle/cream-color-flat-handle-bag.html',
    'zh-tw/products/flathandle/macaron-color-flat-handle-bag.html',
    'zh-tw/products/flathandle/recycled-kraft-flat-handle-sacks.html',
    'zh-tw/products/flathandle/single-color-shopping-bags.html',
    'zh-tw/products/foil.html',
    'zh-tw/products/foil/aluminum-foil-lined-bags.html',
    'zh-tw/products/fruit.html',
    'zh-tw/products/fruit-protection/mango-bag.html',
    'zh-tw/products/greaseproof.html',
    'zh-tw/products/greaseproof/bakery-paper-bag.html',
    'zh-tw/products/greaseproof/bakery-paper-bags.html',
    'zh-tw/products/greaseproof/bakery-series-paper-bags.html',
    'zh-tw/products/greaseproof/bakery-side-window-bag.html',
    'zh-tw/products/greaseproof/banh-mi-paper-bags.html',
    'zh-tw/products/greaseproof/checkered-food-grade-wrap-paper.html',
    'zh-tw/products/greaseproof/deli-wrap.html',
    'zh-tw/products/greaseproof/die-cut-handle-round-hole-bags.html',
    'zh-tw/products/greaseproof/double-layer-paper-bag.html',
    'zh-tw/products/greaseproof/easy-use-die-cut-handle-paper-bags.html',
    'zh-tw/products/greaseproof/fancy-2-side-open-paper-bag.html',
    'zh-tw/products/greaseproof/french-baguette-bag.html',
    'zh-tw/products/greaseproof/fried-bread-stick-paper-bag.html',
    'zh-tw/products/greaseproof/greaseproof-paper-round-hole-bags.html',
    'zh-tw/products/greaseproof/lv-paper-bags.html',
    'zh-tw/products/greaseproof/news-2-side-open-paper-bag.html',
    'zh-tw/products/greaseproof/pfas-free-sandwich-bags.html',
    'zh-tw/products/greaseproof/pinhole-window-greaseproof-bag.html',
    'zh-tw/products/greaseproof/recycled-kraft-merchandise-paper-bags.html',
    'zh-tw/products/greaseproof/round-hole-bags.html',
    'zh-tw/products/greaseproof/small-2-side-open-bag.html',
    'zh-tw/products/greaseproof/solo-snack-bag-round-open.html',
    'zh-tw/products/greaseproof/tear-open-paper-bag.html',
    'zh-tw/products/greaseproof/thank-you-greaseproof-paper-bag.html',
    'zh-tw/products/greaseproof/the-pe-coated-paper-bags.html',
    'zh-tw/products/greaseproof/toast-bags.html',
    'zh-tw/products/greaseproof/toast-bags-have-tearble-line.html',
    'zh-tw/products/kraft.html',
    'zh-tw/products/kraft/8-square-bottom-paper-bag.html',
    'zh-tw/products/kraft/baguette-bakery-bag.html',
    'zh-tw/products/kraft/bakery-series-paper-bags.html',
    'zh-tw/products/kraft/bakery-window-bag.html',
    'zh-tw/products/kraft/christmas-series-square-bottom-paper-bag.html',
    'zh-tw/products/kraft/cream-color-square-bag.html',
    'zh-tw/products/kraft/die-cut-handle-bag.html',
    'zh-tw/products/kraft/flat-handle-grocery-bags.html',
    'zh-tw/products/kraft/hexagonal-bottom-paper-bag.html',
    'zh-tw/products/kraft/merchandise-bags.html',
    'zh-tw/products/kraft/sos-white-take-out-bags.html',
    'zh-tw/products/kraft/square-paper-bag.html',
    'zh-tw/products/kraft/to-go-sos-bags.html',
    'zh-tw/products/others.html',
    'zh-tw/products/others/bakery-side-window-bag.html',
    'zh-tw/products/others/paper-placement.html',
    'zh-tw/products/others/wonderful-time-paper-placemats.html',
    'zh-tw/products/paper-straw/paper-straw.html',
    'zh-tw/products/pe.html',
    'zh-tw/products/pe/burger-pocket-paper-bag.html',
    'zh-tw/products/pe/deli-wrap-paper.html',
    'zh-tw/products/pe-lamination/l-bag.html',
    'zh-tw/products/pe/toast-bags.html',
    'zh-tw/products/straw.html',
    'zh-tw/products/straw/biodegradable-bamboo-straw.html',
    'zh-tw/products/straw/paper-straw-brown.html',
    'zh-tw/products/white.html',
    'zh-tw/products/white-kraft/white-kraft-bag.html',
    'zh-tw/products/white/new-flate-handle-paper-bags.html',
    'zh-tw/products/white/recycled-kraft-grocery-bags.html',
    'zh-tw/products/white/take-out-bags-square-bottom-paper-bag.html',
    'zh-tw/products/white/white-kraft-bags.html',
]

missing = []
for f in files_to_check:
    if not os.path.exists(f):
        missing.append(f)

if missing:
    print("Missing files found:")
    for m in missing:
        print(f" - {m}")
else:
    print("All files exist.")
